stages:
  - validate
  - test
  - build
  - security
  - push
  - deploy
  - verify

# ============================================================
# DEV CONFIGURATION
# ============================================================

variables:

  AWS_REGION: "ap-south-1"

  AWS_ACCOUNT_ID: "064713308676"

  PROJECT_DIR: "company-orders"

  TF_ROOT: "company-orders/infra"

  APP_DIR: "company-orders/app"

  LAMBDA_DIR: "company-orders/lambda"

  PROJECT_NAME: "company-orders"

  ENVIRONMENT: "dev"

  CONTAINER_NAME: "order-service"

  CONTAINER_PORT: "8000"

  HEALTH_ENDPOINT: "/health"

  ECR_REPOSITORY: "company-order-dev-repo"

  # ----------------------------------------------------------
  # Docker
  # ----------------------------------------------------------

  DOCKER_HOST: "tcp://docker:2375"

  DOCKER_TLS_CERTDIR: ""


# ============================================================
# 1. TERRAFORM VALIDATION
# ============================================================

terraform_validate:
  stage: validate

  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]

  script:

    - echo "======================================"
    - echo "Terraform validation"
    - echo "======================================"

    - cd "$TF_ROOT"

    - pwd

    - ls -la

    - terraform fmt -recursive

    - terraform init -backend=false

    - terraform validate

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# ============================================================
# 2. APPLICATION TEST
# ============================================================

application_test:
  stage: test

  image: python:3.12-slim

  before_script:

    - python --version

    - cd "$PROJECT_DIR"

    - pip install --no-cache-dir -r app/requirements.txt

  script:

    - echo "Running application tests..."

    - python -m pytest -q

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# ============================================================
# 3. BUILD DOCKER IMAGE
# ============================================================

docker_build:
  stage: build

  image:
    name: docker:27

  services:
    - name: docker:27-dind
      command:
        - "--tls=false"

  before_script:

    - docker info

  script:

    - echo "======================================"
    - echo "Building Docker image"
    - echo "======================================"

    - export IMAGE_TAG="${CI_COMMIT_SHORT_SHA}"

    - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}"

    - echo "IMAGE URI:"
    - echo "${IMAGE_URI}"

    - cd "$APP_DIR"

    - docker build --pull -t "${IMAGE_URI}" .

    - docker save "${IMAGE_URI}" -o image.tar

  artifacts:

    paths:
      - company-orders/image.tar

    expire_in: 1 hour

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# ============================================================
# 5. CONTAINER SECURITY SCAN
# ============================================================

container_security_scan:
  stage: security

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  needs:
    - job: docker_build
      artifacts: true

  script:

    - echo "======================================"
    - echo "Trivy container security scan"
    - echo "======================================"

    - trivy image --input company-orders/image.tar --severity HIGH,CRITICAL --ignore-unfixed --exit-code 1

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# ============================================================
# 6. PUSH IMAGE TO ECR
# ============================================================

push_to_ecr:
  stage: push

  image:
    name: docker:27

  services:
    - name: docker:27-dind
      command:
        - "--tls=false"

  needs:
    - job: docker_build
      artifacts: true

    - job: container_security_scan

  before_script:

    - apk add --no-cache aws-cli

    - aws --version

    - aws sts get-caller-identity

    - export ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

    - echo "Logging into ECR..."

    - aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${ECR_REGISTRY}"

  script:

    - export IMAGE_TAG="${CI_COMMIT_SHORT_SHA}"

    - export IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

    - docker load -i company-orders/image.tar

    - echo "Pushing:"
    - echo "${IMAGE_URI}"

    - docker push "${IMAGE_URI}"

    - echo "IMAGE_TAG=${IMAGE_TAG}" > build.env

    - echo "IMAGE_URI=${IMAGE_URI}" >> build.env

  artifacts:

    reports:
      dotenv: build.env

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


# ============================================================
# 7. DEPLOY DEV
# ============================================================

deploy_dev:
  stage: deploy

  image:
    name: amazon/aws-cli:2
    entrypoint: [""]

  needs:
    - job: push_to_ecr
      artifacts: true

  before_script:

    - aws --version

    - aws sts get-caller-identity

  script:

    - echo "======================================"
    - echo "Deploying DEV"
    - echo "======================================"

    - echo "Image:"
    - echo "${IMAGE_URI}"


    # --------------------------------------------------------
    # Find ASG
    # --------------------------------------------------------

    - |
      ASG_NAME="${PROJECT_NAME}-${ENVIRONMENT}-asg"

      echo "ASG:"
      echo "${ASG_NAME}"


    # --------------------------------------------------------
    # Get EC2 instances from ASG
    # --------------------------------------------------------

    - |
      INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups --region "${AWS_REGION}" --auto-scaling-group-names "${ASG_NAME}" --query 'AutoScalingGroups[0].Instances[].InstanceId' --output text)

      echo "EC2 instances:"
      echo "${INSTANCE_IDS}"


    # --------------------------------------------------------
    # Make sure instances exist
    # --------------------------------------------------------

    - |
      if [ -z "${INSTANCE_IDS}" ] || [ "${INSTANCE_IDS}" = "None" ]; then
        echo "ERROR: No EC2 instances found in ASG."
        exit 1
      fi


    # --------------------------------------------------------
    # Deploy using AWS Systems Manager
    # --------------------------------------------------------

    - |
      for INSTANCE_ID in ${INSTANCE_IDS}; do

        echo "--------------------------------------"
        echo "Deploying to ${INSTANCE_ID}"
        echo "--------------------------------------"

        COMMAND_ID=$(aws ssm send-command --region "${AWS_REGION}" --instance-ids "${INSTANCE_ID}" --document-name "AWS-RunShellScript" --comment "Deploy ${IMAGE_TAG}" --parameters commands="aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com;

            docker pull ${IMAGE_URI};

            docker stop ${CONTAINER_NAME} || true;

            docker rm ${CONTAINER_NAME} || true;

            docker run -d --restart unless-stopped --name ${CONTAINER_NAME} -p ${CONTAINER_PORT}:${CONTAINER_PORT} ${IMAGE_URI};
          "--query 'Command.CommandId' --output text)"

        echo "SSM Command ID:"
        echo "${COMMAND_ID}"

      done


# ============================================================
# 8. VERIFY DEV
# ============================================================

verify_dev:
  stage: verify

  image:
    name: curlimages/curl:8.10.1
    entrypoint: [""]

  needs:
    - job: deploy_dev

  script:

    - echo "======================================"
    - echo "Checking DEV application health"
    - echo "======================================"


    - |
      for i in $(seq 1 30); do

        HTTP_CODE=$(curl --silent --output /dev/null --write-out "%{http_code}" --max-time 10 "${API_URL}${HEALTH_ENDPOINT}" || true)

        echo "Attempt ${i}: HTTP ${HTTP_CODE}"

        if [ "${HTTP_CODE}" = "200" ]; then

          echo "======================================"
          echo "DEV DEPLOYMENT SUCCESSFUL"
          echo "======================================"

          exit 0

        fi

        sleep 10

      done


    - echo "======================================"
    - echo "DEV DEPLOYMENT FAILED"
    - echo "======================================"

    - exit 1

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'